#  data encryption and decryption

- ENCRYPTION is a security method in which information is encoded in such a way that only aurthorised user can read it.it uses encryption algorithim to generate cipher text can only read if decrypted
- DECRYPTION:
            decryption is the process of taking encode or encrypted text and convertion of it back into text that you or the computer can read and understand
- types
       symmetric(private key): it uses a single key that will be shared among the people who need to receive the message
 - assymetric key(public key):
                             assymetric encryption uses a pair of public key and a private key to encrypt and decrypt messages
                             

#function to generate key for encryption

In [12]:
from random import randint
def generatemarks(n,lb,ub):
    with open('DataFiles/marks.txt','w')as f:
        for i in range(0,n):
            r=randint(lb,ub)
            f.write(str(r)+'/n')
    return
generatemarks(10000,0,100)

In [13]:
keypath='DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w')as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+''+str(i+4)+'\n')
            else:
                f.write(str(i)+''+str(i-6)+'\n')
        return
generatekey(keypath)

In [10]:
#function to decrypt a datafile
keyfile='DataFiles/key.txt'
def dictionarykeyfile(key file):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
def encryptMarksdata (data file,keyfile):
    #construct a dictionary for key data
    key=dictionarykeyfile(keyfile)
    with open('DataFiles/encryptedMarks.txt','w')as f:
        for mark in filedata:
            line=''
            for n in mark:
                line+=key[n]
            f.write(line+'\n')
            return
datafile='DataFiles/marks.txt'
encryptMarksData(datafile,keyfile)

SyntaxError: invalid syntax (<ipython-input-10-9e34d13c15af>, line 3)

In [8]:
def decryptMarksData(encryptedfile,keyfile):
    key=dictionarykeyFile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encrypteddata,'r')as f:
          encrypteddata=f.read().split('/n')
    with open('DataFiles/DecryptedMarks.txt','w')as f:
         for encryptedmarks in encrypteddata:
             line=''
        for n in encryptedmark:
                line+=newkey[n]
                f.write(line+'\n')
    return
encryptedfile='DataFiles/encryptedMarks.txt'
import timeit
st=timeit.default_timer()
decryptedMarkssData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 11)

In [1]:
import numpy as np
li={1,2,3,4,0}
a=np.array(li)
a

array({0, 1, 2, 3, 4}, dtype=object)

In [3]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
import numpy as np
a2=np.arange(10000)
print (a2)
a2.ndim
a2.shape

[   0    1    2 ... 9997 9998 9999]


(10000,)

In [5]:
a2=np.arange(10000).reshape(100,100)
print (a2)


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [14]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,9).reshape(2,3)
print(a,)
print (b,'\n')
print(a+b)
print(a/b)


ValueError: cannot reshape array of size 4 into shape (2,3)